const assert=require('node:assert/strict');
const {run,shot}=require('./journey-render-audit.cjs');
run('SFX.toggle();openMerchantLab();');
assert.equal(run('mode'),'merchant');
assert.equal(run('new Set(merchantShop.stock.filter(x=>x.id).map(x=>x.id)).size'),3);
const stock=run('JSON.stringify(merchantShop.stock)');
run("setMode('run');openMerchantShop('lab')");assert.equal(run('JSON.stringify(merchantShop.stock)'),stock);
const id=run('merchantShop.stock[0].id');
run('gold=0');assert.equal(run('buyMerchantItem()'),false);assert.equal(run('relics.filter(Boolean).length'),0);
run('gold=120');assert.equal(run('buyMerchantItem()'),true);
assert.equal(run('gold'),90);assert.equal(run(`hasRelic('${id}')`),true);
assert.equal(run('buyMerchantItem()'),false);assert.equal(run('gold'),90);
run('paused=true;updateMerchantShop(3)');assert.equal(run('merchantShop.clock'),0);
run('paused=false;updateMerchantShop(3)');assert.equal(run('merchantShop.phase'),'browse');
assert.equal(run('buyMerchantItem()'),false);
run('merchantShop.selected=2');const hp=run('player.currentHealthUnits');
assert.equal(run('buyMerchantItem()'),true);assert.ok(run('player.currentHealthUnits')>hp);
assert.ok(run('player.currentHealthUnits<=player.maxHealthUnits'));
run('updateMerchantShop(3);merchantShop.selected=3');const hidden=run('merchantShop.stock[3].id');
assert.equal(run('buyMerchantItem()'),true);assert.equal(run(`hasRelic('${hidden}')`),true);
run("updateMerchantShop(3);setMode('run');openMerchantShop('lab')");
assert.equal(run('merchantShop.stock[0].sold'),true,'revisit cannot restock');
run('openMerchantLab();player.currentHealthUnits=player.maxHealthUnits;merchantShop.selected=2');
assert.equal(run('buyMerchantItem()'),false);assert.equal(run('gold'),120);
run('merchantShop.selected=0;relics=ARTIFACT_IDS.filter(id=>id!==merchantShop.stock[0].id).slice(0,5).map(id=>ARTIFACT_DEFS[id].create());syncArtifactCache()');
const relics=run('JSON.stringify(relics)');assert.equal(run('buyMerchantItem()'),false);
assert.equal(run('JSON.stringify(relics)'),relics);assert.equal(run('gold'),120);
run('openMerchantLab();');shot('merchant-browse','');
run('buyMerchantItem();updateMerchantShop(.9)');shot('merchant-handoff','');
run('updateMerchantShop(2)');shot('merchant-sold','');
run('resetRun();');assert.equal(run('merchantShop'),null);assert.equal(run('merchantVisits.size'),0);
console.log('MERCHANT_OK seeded stock, no duplicate offers, atomic purchase, full bag/health/poor guards, healing, mystery, pause, sold revisit, reset');
