const assert=require('node:assert/strict');
const {run,shot}=require('./journey-render-audit.cjs');
run('SFX.toggle();startJourneyWithSeed(647486904);gold=200;scrap=20;startBoss();setMode("boss");squire.present=true;boss.hp=0;defeatBoss();boss.stateT=2.6;updateBoss(.016);');
assert.equal(run('mode'),'town');assert.equal(run('squire.present'),false);assert.equal(run('loop'),1);
const distance=run('dist');run('update(1)');assert.equal(run('dist'),distance);
shot('town-arrival','');
run('const firstTownCanvas=townSceneCache.canvas;perfNow=2;render();');
assert.equal(run('townSceneCache.canvas===firstTownCanvas'),true,'idle must reuse detailed architecture');
assert.ok(run('townSceneCache.canvas.width>=480*viewScale'),'cache must preserve display resolution');
run('const priorTownScale=viewScale;viewScale*=1.5;render();');
assert.equal(run('townSceneCache.canvas===firstTownCanvas'),false,'resize must rebuild at the new resolution');
run('viewScale=priorTownScale;render();');
run('townTap({x:90,y:450});paused=true;updateTown(1)');assert.equal(run('mode'),'town');
run('paused=false;updateTown(.4)');assert.equal(run('mode'),'shop');
run('blacksmithShop.random=()=>.999;beginSmithUpgrade();updateBlacksmithShop(5);shopTap({x:240,y:680});');
const skill=run('JSON.stringify(runSkills[0])'),balance=run('gold');
run('const savedForge=blacksmithShop;shopTap({x:240,y:750});townTap({x:90,y:450});updateTown(.4)');
assert.equal(run('blacksmithShop===savedForge'),true);assert.equal(run('gold'),balance);
assert.equal(run('JSON.stringify(runSkills[0])'),skill);assert.equal(run('blacksmithShop.attempts'),1);
run('shopTap({x:240,y:750});townTap({x:390,y:400});updateTown(.4)');assert.equal(run('mode'),'merchant');
assert.equal(run('merchantShop.townId'),run('townVisit.id'));shot('town-general-store','');
run('buyMerchantItem();updateMerchantShop(2);rerollMerchantStock();updateMerchantShop(.5)');
const stock=run('JSON.stringify(merchantShop.stock)'),price=run('merchantRerollCost()'),gold=run('gold');
run('merchantTap({x:240,y:760});townTap({x:390,y:400});updateTown(.4)');
assert.equal(run('JSON.stringify(merchantShop.stock)'),stock);assert.equal(run('merchantRerollCost()'),price);assert.equal(run('gold'),gold);
run('merchantTap({x:240,y:760});townTap({x:90,y:240})');assert.equal(run('townVisit.dialog'),null);
assert.equal(run('JSON.stringify(Object.keys(TOWN_PLACES))'),JSON.stringify(['smith','store']));
run('townTap({x:240,y:705});townTap({x:240,y:760})');assert.equal(run('mode'),'town');
run('townTap({x:240,y:705});townTap({x:240,y:705});townTap({x:240,y:705})');
assert.equal(run('mode'),'run');assert.equal(run('loop'),2);assert.equal(run('journeyRoute.stage'),2);
assert.equal(run('gold'),gold);assert.equal(run('JSON.stringify(runSkills[0])'),skill);
run('openTown()');assert.equal(run('townVisit.chapter.id'),'stoneford');assert.equal(run('townVisit.forge'),null);shot('town-stoneford','');
run('loop=3;openTown()');shot('town-emberwatch','');
run('resetRun()');assert.equal(run('townVisit'),null);
// PLAY now launches Journey and reaches town; standalone laboratories are unchanged.
run('debugRun=false;startRun(0);RUN_POLICY().afterBoss()');assert.equal(run('mode'),'town');
run('openBlacksmithLab()');assert.equal(run('blacksmithShop.lab!==undefined'),true);
run('openMerchantLab()');assert.equal(run('merchantShop.lab'),true);
console.log('TOWN_OK boss arrival, no distance advance, pause, forge RNG/build retention, store sold stock/reroll retention, exactly two building entrances, departure confirmation/single advance, chapter appearance, primary PLAY/lab isolation');
